[2024-09-29T07:55:59.856+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.create_dims manual__2024-09-29T07:55:33.193072+00:00 [queued]>
[2024-09-29T07:56:00.219+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.create_dims manual__2024-09-29T07:55:33.193072+00:00 [queued]>
[2024-09-29T07:56:00.293+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T07:56:00.606+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_dims> on 2024-09-29 07:55:33.193072+00:00
[2024-09-29T07:56:01.128+0000] {standard_task_runner.py:57} INFO - Started process 7047 to run task
[2024-09-29T07:56:01.222+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'create_dims', 'manual__2024-09-29T07:55:33.193072+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpbiym08o_']
[2024-09-29T07:56:01.304+0000] {standard_task_runner.py:85} INFO - Job 176: Subtask create_dims
[2024-09-29T07:56:03.193+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.create_dims manual__2024-09-29T07:55:33.193072+00:00 [running]> on host 5096eb060c49
[2024-09-29T07:56:04.168+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'create_dims', field 'sql'. Template: 'dims.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 154, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dims.sql
[2024-09-29T07:56:04.219+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1645, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2283, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1245, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 154, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: dims.sql
[2024-09-29T07:56:04.485+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=create_dims, execution_date=20240929T075533, start_date=20240929T075559, end_date=20240929T075604
[2024-09-29T07:56:04.896+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 176 for task create_dims (dims.sql; 7047)
[2024-09-29T07:56:05.506+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-29T07:56:06.310+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
