[2024-09-29T07:57:20.610+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T07:55:33.193072+00:00 [queued]>
[2024-09-29T07:57:20.632+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T07:55:33.193072+00:00 [queued]>
[2024-09-29T07:57:20.633+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T07:57:20.676+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_flats> on 2024-09-29 07:55:33.193072+00:00
[2024-09-29T07:57:20.722+0000] {standard_task_runner.py:57} INFO - Started process 7109 to run task
[2024-09-29T07:57:20.749+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'get_flats', 'manual__2024-09-29T07:55:33.193072+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmp7mqnn4r3']
[2024-09-29T07:57:20.758+0000] {standard_task_runner.py:85} INFO - Job 186: Subtask get_flats
[2024-09-29T07:57:20.966+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.get_flats manual__2024-09-29T07:55:33.193072+00:00 [running]> on host 5096eb060c49
[2024-09-29T07:57:21.697+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='get_flats' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T07:55:33.193072+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T07:55:33.193072+00:00'
[2024-09-29T07:57:21.757+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-1:
[2024-09-29T07:57:21.758+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T07:57:21.758+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T07:57:21.760+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T07:57:21.761+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T07:57:21.762+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T07:57:21.763+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 118, in get_flat
[2024-09-29T07:57:21.765+0000] {logging_mixin.py:151} WARNING -     for k, url in urls:
[2024-09-29T07:57:21.765+0000] {logging_mixin.py:151} WARNING - ValueError: too many values to unpack (expected 2)
[2024-09-29T07:57:21.767+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parser.py", line 169, in get_flats
    t.start()
  File "/usr/local/lib/python3.8/threading.py", line 848, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
[2024-09-29T07:57:21.795+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=get_flats, execution_date=20240929T075533, start_date=20240929T075720, end_date=20240929T075721
[2024-09-29T07:57:21.844+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 186 for task get_flats (threads can only be started once; 7109)
[2024-09-29T07:57:21.886+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-29T07:57:21.988+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
