[2024-09-29T07:59:04.094+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.create_facts manual__2024-09-29T07:58:37.633706+00:00 [queued]>
[2024-09-29T07:59:04.166+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.create_facts manual__2024-09-29T07:58:37.633706+00:00 [queued]>
[2024-09-29T07:59:04.181+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T07:59:04.329+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_facts> on 2024-09-29 07:58:37.633706+00:00
[2024-09-29T07:59:04.394+0000] {standard_task_runner.py:57} INFO - Started process 7205 to run task
[2024-09-29T07:59:04.444+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'create_facts', 'manual__2024-09-29T07:58:37.633706+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpi6op1_3j']
[2024-09-29T07:59:04.478+0000] {standard_task_runner.py:85} INFO - Job 190: Subtask create_facts
[2024-09-29T07:59:05.038+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.create_facts manual__2024-09-29T07:58:37.633706+00:00 [running]> on host 5096eb060c49
[2024-09-29T07:59:05.714+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'create_facts', field 'sql'. Template: 'facts.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 154, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: facts.sql
[2024-09-29T07:59:05.737+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1645, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2283, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1245, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 154, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: facts.sql
[2024-09-29T07:59:05.850+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=create_facts, execution_date=20240929T075837, start_date=20240929T075904, end_date=20240929T075905
[2024-09-29T07:59:05.946+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 190 for task create_facts (facts.sql; 7205)
[2024-09-29T07:59:06.013+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-29T07:59:06.867+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
