[2024-09-26T16:40:05.376+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.transform_to_dims manual__2024-09-26T16:39:24.432511+00:00 [queued]>
[2024-09-26T16:40:05.394+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.transform_to_dims manual__2024-09-26T16:39:24.432511+00:00 [queued]>
[2024-09-26T16:40:05.395+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-26T16:40:05.420+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_to_dims> on 2024-09-26 16:39:24.432511+00:00
[2024-09-26T16:40:05.455+0000] {standard_task_runner.py:57} INFO - Started process 354 to run task
[2024-09-26T16:40:05.471+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'transform_to_dims', 'manual__2024-09-26T16:39:24.432511+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmp3rmckujl']
[2024-09-26T16:40:05.478+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask transform_to_dims
[2024-09-26T16:40:05.603+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.transform_to_dims manual__2024-09-26T16:39:24.432511+00:00 [running]> on host 5096eb060c49
[2024-09-26T16:40:05.773+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='transform_to_dims' AIRFLOW_CTX_EXECUTION_DATE='2024-09-26T16:39:24.432511+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-26T16:39:24.432511+00:00'
[2024-09-26T16:40:05.843+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 168, in create_flat_dims
    dim_flat_params = flats_df[
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5877, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5941, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['rooms'] not in index"
[2024-09-26T16:40:05.906+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=transform_to_dims, execution_date=20240926T163924, start_date=20240926T164005, end_date=20240926T164005
[2024-09-26T16:40:05.953+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task transform_to_dims ("['rooms'] not in index"; 354)
[2024-09-26T16:40:05.999+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-26T16:40:06.100+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
