[2024-09-29T08:22:16.402+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T08:21:18.325782+00:00 [queued]>
[2024-09-29T08:22:16.436+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.get_flats manual__2024-09-29T08:21:18.325782+00:00 [queued]>
[2024-09-29T08:22:16.441+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T08:22:16.513+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_flats> on 2024-09-29 08:21:18.325782+00:00
[2024-09-29T08:22:16.625+0000] {standard_task_runner.py:57} INFO - Started process 7606 to run task
[2024-09-29T08:22:16.762+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'get_flats', 'manual__2024-09-29T08:21:18.325782+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpu2tmsaak']
[2024-09-29T08:22:16.841+0000] {standard_task_runner.py:85} INFO - Job 201: Subtask get_flats
[2024-09-29T08:22:17.677+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.get_flats manual__2024-09-29T08:21:18.325782+00:00 [running]> on host 5096eb060c49
[2024-09-29T08:22:18.337+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='get_flats' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T08:21:18.325782+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T08:21:18.325782+00:00'
[2024-09-29T08:22:18.469+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-1:
[2024-09-29T08:22:18.470+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.470+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.472+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.472+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.474+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.475+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.479+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.487+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.494+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.495+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.500+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.503+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.506+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.509+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.511+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.513+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.519+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.521+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.527+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-2:
[2024-09-29T08:22:18.529+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.536+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.539+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.541+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.543+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.546+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.549+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.551+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.554+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.557+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.559+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.560+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.562+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.565+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.569+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.575+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.579+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.588+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.609+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-3:
[2024-09-29T08:22:18.613+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.615+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.617+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.618+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.620+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.623+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.626+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.627+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.628+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.629+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.633+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.635+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.636+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.637+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.638+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.639+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.640+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.641+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.643+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-4:
[2024-09-29T08:22:18.644+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.644+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.645+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.646+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.647+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.648+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.649+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.650+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.652+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.652+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.654+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.655+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.656+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.657+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.660+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.662+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.664+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.666+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.669+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-5:
[2024-09-29T08:22:18.670+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.670+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.672+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.673+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.674+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.674+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.675+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.676+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.677+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.677+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.678+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.679+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.679+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.680+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.680+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.681+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.683+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.684+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.687+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-6:
[2024-09-29T08:22:18.688+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.689+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.690+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.692+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.694+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.694+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.695+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.696+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.696+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.697+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.698+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.699+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.700+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.701+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.702+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.703+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.705+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.705+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.708+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-7:
[2024-09-29T08:22:18.709+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.709+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.711+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.711+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.712+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.713+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.717+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.718+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.719+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.720+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.726+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.727+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.728+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.728+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.729+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.731+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.733+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.734+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.736+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-8:
[2024-09-29T08:22:18.737+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.738+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.740+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.741+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.743+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.744+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.746+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.746+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.747+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.747+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.748+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.750+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.754+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.780+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.792+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.800+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.802+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.803+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.807+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-9:
[2024-09-29T08:22:18.808+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.808+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.809+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.810+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.811+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.811+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.813+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.815+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.817+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.817+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.818+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.818+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.820+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.821+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.825+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.826+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.831+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.833+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.836+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-10:
[2024-09-29T08:22:18.838+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.840+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.841+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.842+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.846+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.847+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.849+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.849+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.850+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.851+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.852+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.854+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.857+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.857+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.860+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.863+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.864+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.866+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.869+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-11:
[2024-09-29T08:22:18.869+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.870+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.872+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.873+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.875+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.876+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.877+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.878+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.880+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.880+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.880+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.881+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.881+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.882+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.883+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.884+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.884+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.886+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.894+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-12:
[2024-09-29T08:22:18.898+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.900+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.916+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.919+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.936+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.943+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.945+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.946+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.947+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.948+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.949+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.951+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.952+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.952+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.953+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.955+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.957+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.959+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.964+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-13:
[2024-09-29T08:22:18.969+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:18.970+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:18.972+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:18.972+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:18.973+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:18.975+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:18.976+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:18.976+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:18.978+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:18.978+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:18.978+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:18.979+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:18.980+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:18.981+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:18.983+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:18.984+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:18.985+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:18.986+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:18.990+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-14:
[2024-09-29T08:22:18.991+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.000+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.002+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.004+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.005+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.006+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.008+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.009+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.010+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.010+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.011+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.011+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.013+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.013+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.015+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.016+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.017+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.018+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.020+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-15:
[2024-09-29T08:22:19.020+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.021+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.023+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.025+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.026+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.027+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.029+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.031+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.032+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.034+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.037+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.038+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.040+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.041+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.043+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.044+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.046+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.047+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.049+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-16:
[2024-09-29T08:22:19.051+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.053+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.059+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.078+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.081+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.083+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.088+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.090+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.091+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.091+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.092+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.093+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.095+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.108+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.111+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.113+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.114+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.117+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.121+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-17:
[2024-09-29T08:22:19.122+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.140+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.168+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.171+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.174+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.180+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.190+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.196+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.201+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.203+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.205+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.206+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.209+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.210+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.213+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.218+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.224+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.227+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.230+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-18:
[2024-09-29T08:22:19.233+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.235+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.237+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.239+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.242+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.245+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.252+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.258+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.259+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.260+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.262+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.262+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.267+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.267+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.270+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.272+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.275+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.277+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.284+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-19:
[2024-09-29T08:22:19.305+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.310+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.315+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.318+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.320+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.324+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.326+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.328+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.334+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.340+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.342+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.344+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.346+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.348+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.350+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.355+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.358+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.361+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.370+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-20:
[2024-09-29T08:22:19.374+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.378+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.382+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.383+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.391+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.393+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.397+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.399+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.402+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.405+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.411+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.414+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.418+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.419+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.426+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.428+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.449+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.453+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.458+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-21:
[2024-09-29T08:22:19.461+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.462+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.463+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.467+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.469+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.470+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.473+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.474+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.476+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.477+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.478+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.479+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.480+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.481+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.483+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.485+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.488+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.489+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.491+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-22:
[2024-09-29T08:22:19.492+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.493+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.495+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.496+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.497+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.498+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.500+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.501+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.502+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.503+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.504+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.506+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.507+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.508+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.510+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.510+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.513+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.516+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.519+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-23:
[2024-09-29T08:22:19.521+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.522+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.524+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.525+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.526+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.527+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.530+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.532+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.534+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.534+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.536+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.536+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.538+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.539+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.540+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.541+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.542+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.543+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.547+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-24:
[2024-09-29T08:22:19.549+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.551+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.554+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.555+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.558+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.563+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.566+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.567+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.568+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.569+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.570+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.571+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.573+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.575+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.577+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.579+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.582+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.583+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.587+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-25:
[2024-09-29T08:22:19.588+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.589+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.590+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.590+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.591+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.592+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.593+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.593+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.594+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.595+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.596+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.596+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.597+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.598+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.600+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.600+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.602+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.603+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.607+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-26:
[2024-09-29T08:22:19.609+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.609+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.611+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.613+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.615+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.615+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.617+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.617+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.618+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.618+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.619+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.620+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.621+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.622+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.623+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.623+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.624+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.625+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.626+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-27:
[2024-09-29T08:22:19.627+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.627+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.628+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.629+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.630+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.630+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.632+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.633+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.635+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.637+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.638+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.638+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.640+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.641+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.643+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.644+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.645+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.645+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.647+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-28:
[2024-09-29T08:22:19.648+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.648+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.649+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.650+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.650+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.651+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.652+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.653+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.653+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.654+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.654+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.655+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.655+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.656+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.657+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.657+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.658+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.658+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.660+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-29:
[2024-09-29T08:22:19.660+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.661+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.662+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.662+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.664+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.665+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.667+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.669+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.670+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.671+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.672+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.672+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.673+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.674+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.675+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.676+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.677+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.677+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.679+0000] {logging_mixin.py:151} WARNING - Exception in thread Thread-30:
[2024-09-29T08:22:19.679+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-09-29T08:22:19.680+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[2024-09-29T08:22:19.681+0000] {logging_mixin.py:151} WARNING -     self.run()
[2024-09-29T08:22:19.681+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/threading.py", line 870, in run
[2024-09-29T08:22:19.682+0000] {logging_mixin.py:151} WARNING -     self._target(*self._args, **self._kwargs)
[2024-09-29T08:22:19.683+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/parser.py", line 121, in get_flat
[2024-09-29T08:22:19.684+0000] {logging_mixin.py:151} WARNING -     r = requests.get(url)
[2024-09-29T08:22:19.685+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
[2024-09-29T08:22:19.686+0000] {logging_mixin.py:151} WARNING -     return request("get", url, params=params, **kwargs)
[2024-09-29T08:22:19.686+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
[2024-09-29T08:22:19.687+0000] {logging_mixin.py:151} WARNING -     return session.request(method=method, url=url, **kwargs)
[2024-09-29T08:22:19.687+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2024-09-29T08:22:19.688+0000] {logging_mixin.py:151} WARNING -     resp = self.send(prep, **send_kwargs)
[2024-09-29T08:22:19.689+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
[2024-09-29T08:22:19.690+0000] {logging_mixin.py:151} WARNING -     adapter = self.get_adapter(url=request.url)
[2024-09-29T08:22:19.691+0000] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 794, in get_adapter
[2024-09-29T08:22:19.692+0000] {logging_mixin.py:151} WARNING -     raise InvalidSchema(f"No connection adapters were found for {url!r}")
[2024-09-29T08:22:19.693+0000] {logging_mixin.py:151} WARNING - requests.exceptions.InvalidSchema: No connection adapters were found for 'Unnamed: 0'
[2024-09-29T08:22:19.695+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-09-29T08:22:19.733+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=flats, task_id=get_flats, execution_date=20240929T082118, start_date=20240929T082216, end_date=20240929T082219
[2024-09-29T08:22:19.829+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-29T08:22:19.985+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
