[2024-09-22T09:40:42.935+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.get_links manual__2024-09-22T09:40:36.936570+00:00 [queued]>
[2024-09-22T09:40:42.943+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.get_links manual__2024-09-22T09:40:36.936570+00:00 [queued]>
[2024-09-22T09:40:42.943+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-22T09:40:42.959+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_links> on 2024-09-22 09:40:36.936570+00:00
[2024-09-22T09:40:42.964+0000] {standard_task_runner.py:57} INFO - Started process 235 to run task
[2024-09-22T09:40:42.969+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'get_links', 'manual__2024-09-22T09:40:36.936570+00:00', '--job-id', '1005', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpg95yzplz']
[2024-09-22T09:40:42.972+0000] {standard_task_runner.py:85} INFO - Job 1005: Subtask get_links
[2024-09-22T09:40:43.024+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.get_links manual__2024-09-22T09:40:36.936570+00:00 [running]> on host 1646e3dc8472
[2024-09-22T09:40:43.096+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='get_links' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T09:40:36.936570+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T09:40:36.936570+00:00'
[2024-09-22T09:40:45.582+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parser.py", line 56, in get_links
    df.to_csv('data/parser/links.csv')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data/parser'
[2024-09-22T09:40:45.610+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=get_links, execution_date=20240922T094036, start_date=20240922T094042, end_date=20240922T094045
[2024-09-22T09:40:45.632+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1005 for task get_links (Cannot save file into a non-existent directory: 'data/parser'; 235)
[2024-09-22T09:40:45.657+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-22T09:40:45.695+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
