[2024-09-29T07:32:33.394+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flats.create_dims manual__2024-09-29T07:30:54.887347+00:00 [queued]>
[2024-09-29T07:32:33.403+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flats.create_dims manual__2024-09-29T07:30:54.887347+00:00 [queued]>
[2024-09-29T07:32:33.403+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-29T07:32:33.415+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_dims> on 2024-09-29 07:30:54.887347+00:00
[2024-09-29T07:32:33.422+0000] {standard_task_runner.py:57} INFO - Started process 6622 to run task
[2024-09-29T07:32:33.426+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flats', 'create_dims', 'manual__2024-09-29T07:30:54.887347+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/flats.py', '--cfg-path', '/tmp/tmpmjgiuoeg']
[2024-09-29T07:32:33.431+0000] {standard_task_runner.py:85} INFO - Job 170: Subtask create_dims
[2024-09-29T07:32:33.481+0000] {task_command.py:415} INFO - Running <TaskInstance: flats.create_dims manual__2024-09-29T07:30:54.887347+00:00 [running]> on host 5096eb060c49
[2024-09-29T07:32:33.734+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flats' AIRFLOW_CTX_TASK_ID='create_dims' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T07:30:54.887347+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-29T07:30:54.887347+00:00'
[2024-09-29T07:32:33.742+0000] {sql.py:274} INFO - Executing: 
[2024-09-29T07:32:33.770+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-09-29T07:32:34.224+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 383, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2024-09-29T07:32:34.242+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flats, task_id=create_dims, execution_date=20240929T073054, start_date=20240929T073233, end_date=20240929T073234
[2024-09-29T07:32:34.267+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 170 for task create_dims (List of SQL statements is empty; 6622)
[2024-09-29T07:32:34.299+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-29T07:32:34.362+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
